### ISSUE TITLE
Schema must be contructed from file

### ISSUE THREAD

**Issue by Kerollmops** [Kerollmops/MeiliDB#47]
We must be able to create a Schema from a file. The format could be [toml](https://github.com/toml-lang/toml) for example.

It could be something of this form, the order in which the attributes are declared is important.
[There is a pull request about that](https://github.com/alexcrichton/toml-rs/pull/242) in the toml repository.

```toml
identifer = "id"

[attributes."id"]
stored = true

[attributes."title"]
stored = true
indexed = true

[attributes."description"]
stored = true
indexed = true

[attributes."image"]
stored = true
```
